In [1]:
import pandas as pd #pip install pandas
import numpy as np 
#pip install -U scikit-learn
import pickle
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [2]:
df = pd.read_csv(r'C:/Users/siddh/OneDrive/Desktop/Git/AI-ML/Task 3/heart_attack.csv')
df.head(3)

ID      State  Age HeartAttack  Gender  Cholesterol SmokingHabits  \
0   1  Pekanbaru   32          No    Male          179        Smoker   
1   2   Makassar   15         Yes  Female          201    Non-smoker   
2   3   Surabaya   41          No  Female          167    Non-smoker   

  PhysicalActivity   BMI Hypertension  ... EducationLevel MaritalStatus  \
0             High  19.1          Yes  ...      Secondary        Single   
1             High  26.9           No  ...      Secondary       Married   
2         Moderate  29.6          Yes  ...        Primary        Single   

  FamilyHistoryHeartDisease IncomeLevel HealthcareAccess SleepHours  \
0                        No      Middle             Good        7.9   
1                        No      Middle          Average        8.5   
2                        No      Middle             Poor        7.3   

  UrbanOrRural AirQualityIndex PollutionLevel EmploymentStatus  
0        Urban              73           High       Unemployed  
1        Urban             266       Moderate       Unemployed  
2        Urban             132       Moderate         Employed  

[3 rows x 25 columns]

In [3]:
df.describe

<bound method NDFrame.describe of             ID      State  Age HeartAttack  Gender  Cholesterol SmokingHabits  \
0            1  Pekanbaru   32          No    Male          179        Smoker   
1            2   Makassar   15         Yes  Female          201    Non-smoker   
2            3   Surabaya   41          No  Female          167    Non-smoker   
3            4     Malang   31          No    Male          287        Smoker   
4            5       Bali   19          No    Male          239        Smoker   
...        ...        ...  ...         ...     ...          ...           ...   
170496  170497   Semarang   23          No    Male          295        Smoker   
170497  170498     Malang   25         Yes    Male          172    Non-smoker   
170498  170499  Pekanbaru   64          No    Male          209        Smoker   
170499  170500    Bandung   57          No    Male          150        Smoker   
170500  170501     Malang   29         Yes    Male          230        Smok

In [4]:
df.columns

Index(['ID', 'State', 'Age', 'HeartAttack', 'Gender', 'Cholesterol',
       'SmokingHabits', 'PhysicalActivity', 'BMI', 'Hypertension', 'Diabetes',
       'AlcoholConsumption', 'DietType', 'OccupationType', 'StressLevel',
       'EducationLevel', 'MaritalStatus', 'FamilyHistoryHeartDisease',
       'IncomeLevel', 'HealthcareAccess', 'SleepHours', 'UrbanOrRural',
       'AirQualityIndex', 'PollutionLevel', 'EmploymentStatus'],
      dtype='object')

In [5]:
df.drop(columns= ['ID', 'State','EmploymentStatus','MaritalStatus','FamilyHistoryHeartDisease','AirQualityIndex','HealthcareAccess'], inplace=True )

In [6]:
df.columns

Index(['Age', 'HeartAttack', 'Gender', 'Cholesterol', 'SmokingHabits',
       'PhysicalActivity', 'BMI', 'Hypertension', 'Diabetes',
       'AlcoholConsumption', 'DietType', 'OccupationType', 'StressLevel',
       'EducationLevel', 'IncomeLevel', 'SleepHours', 'UrbanOrRural',
       'PollutionLevel'],
      dtype='object')

In [7]:
df.drop(columns= ['PhysicalActivity', 'BMI','Diabetes','OccupationType','DietType','SleepHours','UrbanOrRural','IncomeLevel','EducationLevel'], inplace=True )

In [8]:
df.columns

Index(['Age', 'HeartAttack', 'Gender', 'Cholesterol', 'SmokingHabits',
       'Hypertension', 'AlcoholConsumption', 'StressLevel', 'PollutionLevel'],
      dtype='object')

In [9]:
df.drop(columns= ['PollutionLevel','StressLevel','PollutionLevel'], inplace=True )

In [10]:
df.columns

Index(['Age', 'HeartAttack', 'Gender', 'Cholesterol', 'SmokingHabits',
       'Hypertension', 'AlcoholConsumption'],
      dtype='object')

In [11]:
df.head(3)

Age HeartAttack  Gender  Cholesterol SmokingHabits Hypertension  \
0   32          No    Male          179        Smoker          Yes   
1   15         Yes  Female          201    Non-smoker           No   
2   41          No  Female          167    Non-smoker          Yes   

  AlcoholConsumption  
0                NaN  
1             Rarely  
2                NaN

In [12]:
d = {"HeartAttack":"Cardiac_Arrest", "Gender":"Sex","SmokingHabits":"Smoker","AlcoholConsumption":"Alcoholic"}
df.rename(columns= d , inplace=True )

In [13]:
df.head(5)

Age Cardiac_Arrest     Sex  Cholesterol      Smoker Hypertension Alcoholic
0   32             No    Male          179      Smoker          Yes       NaN
1   15            Yes  Female          201  Non-smoker           No    Rarely
2   41             No  Female          167  Non-smoker          Yes       NaN
3   31             No    Male          287      Smoker           No    Rarely
4   19             No    Male          239      Smoker           No       NaN

In [14]:
df['Age'].unique

<bound method Series.unique of 0         32
1         15
2         41
3         31
4         19
          ..
170496    23
170497    25
170498    64
170499    57
170500    29
Name: Age, Length: 170501, dtype: int64>

In [15]:
df.isna().sum()

Age                   0
Cardiac_Arrest        0
Sex                   0
Cholesterol           0
Smoker                0
Hypertension          0
Alcoholic         56628
dtype: int64

In [16]:
df.fillna('No')

Age Cardiac_Arrest     Sex  Cholesterol      Smoker Hypertension  \
0        32             No    Male          179      Smoker          Yes   
1        15            Yes  Female          201  Non-smoker           No   
2        41             No  Female          167  Non-smoker          Yes   
3        31             No    Male          287      Smoker           No   
4        19             No    Male          239      Smoker           No   
...     ...            ...     ...          ...         ...          ...   
170496   23             No    Male          295      Smoker           No   
170497   25            Yes    Male          172  Non-smoker          Yes   
170498   64             No    Male          209      Smoker           No   
170499   57             No    Male          150      Smoker           No   
170500   29            Yes    Male          230      Smoker           No   

       Alcoholic  
0             No  
1         Rarely  
2             No  
3         Rarely  
4             No  
...          ...  
170496    Rarely  
170497     Often  
170498        No  
170499    Rarely  
170500        No  

[170501 rows x 7 columns]

In [17]:
df.isna().sum()
df.head(5)

Age Cardiac_Arrest     Sex  Cholesterol      Smoker Hypertension Alcoholic
0   32             No    Male          179      Smoker          Yes       NaN
1   15            Yes  Female          201  Non-smoker           No    Rarely
2   41             No  Female          167  Non-smoker          Yes       NaN
3   31             No    Male          287      Smoker           No    Rarely
4   19             No    Male          239      Smoker           No       NaN

In [18]:

df['Alcoholic'].fillna('Never', inplace=True)

df.isna().sum()

C:\Users\siddh\AppData\Local\Temp\ipykernel_8072\1530889404.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Alcoholic'].fillna('Never', inplace=True)


Age               0
Cardiac_Arrest    0
Sex               0
Cholesterol       0
Smoker            0
Hypertension      0
Alcoholic         0
dtype: int64

In [19]:
df.head(5)


Age Cardiac_Arrest     Sex  Cholesterol      Smoker Hypertension Alcoholic
0   32             No    Male          179      Smoker          Yes     Never
1   15            Yes  Female          201  Non-smoker           No    Rarely
2   41             No  Female          167  Non-smoker          Yes     Never
3   31             No    Male          287      Smoker           No    Rarely
4   19             No    Male          239      Smoker           No     Never

In [20]:
le = LabelEncoder()
df['Cardiac_Arrest'] = le.fit_transform(df['Cardiac_Arrest'])
df['Smoker'] = le.fit_transform(df['Smoker'])
df['Alcoholic'] = le.fit_transform(df['Alcoholic'])
df['Sex'] = le.fit_transform(df['Sex'])
df['Hypertension'] = le.fit_transform(df['Hypertension'])
df.head()

Age  Cardiac_Arrest  Sex  Cholesterol  Smoker  Hypertension  Alcoholic
0   32               0    1          179       1             1          0
1   15               1    0          201       0             0          2
2   41               0    0          167       0             1          0
3   31               0    1          287       1             0          2
4   19               0    1          239       1             0          0

In [21]:
df['Alcoholic'].unique()

array([0, 2, 1])

In [22]:
ss = StandardScaler()

df[['Age','Cholesterol']] = ss.fit_transform(df[['Age','Cholesterol']])

df.head(5)

Age  Cardiac_Arrest  Sex  Cholesterol  Smoker  Hypertension  Alcoholic
0 -0.520953               0    1    -1.053073       1             1          0
1 -1.700187               1    0    -0.544175       0             0          2
2  0.103347               0    0    -1.330654       0             1          0
3 -0.590320               0    1     1.445155       1             0          2
4 -1.422720               0    1     0.334831       1             0          0

In [23]:
X = df[['Sex','Age','Cholesterol','Smoker','Hypertension','Alcoholic']]
Y = df['Cardiac_Arrest']

In [24]:
X_train, X_test, y_train, y_test = train_test_split(X,Y,train_size=0.2)

In [25]:
model = LogisticRegression()
model.fit(X_train,y_train)

LogisticRegression()

In [26]:
y_pred = model.predict(X_test)
print(y_pred)

[0 0 0 ... 0 0 0]


In [27]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [28]:
print(accuracy_score(y_test,y_pred))

0.7502217725676498


In [29]:
print(confusion_matrix(y_test,y_pred))

[[102331      0]
 [ 34070      0]]


In [30]:
model_dt = DecisionTreeClassifier()
model_dt.fit(X_train,y_train)

DecisionTreeClassifier()

In [31]:
model_rf = RandomForestClassifier()
model_rf.fit(X_train,y_train)

RandomForestClassifier()

In [32]:
with open(r'C:/Users/siddh/OneDrive/Desktop/Git/AI-ML/Task 3/heart_attack_model.pkl','wb') as f:
 pickle.dump(model,f)